apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: raas-khi
spec:
  ports:
    - port: 80
      nodePort: 31010
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: sample-app