 version: 2.1
 jobs:
   build:
    docker:
       - image: docker:18.03.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t mynginx .
      - run:
          command: docker image ls     
