 version: 2.1
 jobs:
   build:
    docker:
       - image: docker:18.03.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t sample .
      - run:
          name: Check image
          command: docker image ls
      - run:
          name: Docker Login
          command: docker login --username=${UserName} --password=${Password}
      - run:
          name: Pull image
          command: docker pull sample
          
