 version: 2.1
 jobs:
   build:
    docker:
       - image: docker:18.03.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t sample .
          command: docker push sample
      - run:
          name: Tag
          command: docker tag sample mynginx
      - run:
          name: Check image
          command: docker image ls
          
