 version: 2.1
 jobs:
   build:
    docker:
       - image: docker:18.03.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: Build & Push
          command: docker build -t sample .
      - run:
          name: Tag
          command: docker tag sample mynginx
      - run:
          name: Check image
          command: docker image ls
      - run:
          name: Run image
          command: docker run -d sample
      - run:
          name: Run image
          command: FOR /F %%i in ('docker ps -aqf "ancestor=nginx"') do set id=%%i
           
