apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: raas-khi
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 662637059804.dkr.ecr.ap-northeast-1.amazonaws.com/cios-khi-poc-ecr-app-raas-khi-ap/calculate-score-batch
        ports:
        - containerPort: 80